### ISSUE TITLE
Design YAML for project metadata

### ISSUE THREAD

**Issue by simonwiles** [nanyang-temples/nanyang-data.info#1]
We need a structure for project metadata -- perhaps something as simple as this will do:

```yaml
projectName: <project name>

description: |
  ## Project description

  A description of the project with **markdown** available.
  (Mostly valuable so as to be able to include [links](http://project-upstream.com) and/or images, e.g. ![Project Logo](http://project-upstream.com/logo.png)

contact: email.me@provider.org

credits:
  - person one <optional@email.net>
  - person two <optional@email.net>
  - person one
  
```
